// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtT-VA6hj53pCfUgD63bxH8rS6QAXi-7Q',
    appId: '1:425740148744:web:316a8f412f599c9ed8f1bd',
    messagingSenderId: '425740148744',
    projectId: 'booknow-f1f4f',
    authDomain: 'booknow-f1f4f.firebaseapp.com',
    storageBucket: 'booknow-f1f4f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOaf1DnLWNFKIWtbuPWq7dEPOTbr4_Ym0',
    appId: '1:425740148744:android:6ab447aadef4c33dd8f1bd',
    messagingSenderId: '425740148744',
    projectId: 'booknow-f1f4f',
    storageBucket: 'booknow-f1f4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeGB6xso5gdirzlRXjXKtmMz3AmAfD_P8',
    appId: '1:425740148744:ios:0c6e305d731f06c1d8f1bd',
    messagingSenderId: '425740148744',
    projectId: 'booknow-f1f4f',
    storageBucket: 'booknow-f1f4f.firebasestorage.app',
    iosBundleId: 'com.booknow.com',
  );
}
