name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Docker image version (e.g., v1.2.3)"
        required: true
        default: "v1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/book-now
          VERSION_TAG=${{ github.event.inputs.version }}

          echo "Building image: $IMAGE_NAME:$VERSION_TAG"
          docker build -t $IMAGE_NAME:$VERSION_TAG .

      # Push Docker image
      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/book-now
          VERSION_TAG=${{ github.event.inputs.version }}

          echo "Pushing image: $IMAGE_NAME:$VERSION_TAG"
          docker push $IMAGE_NAME:$VERSION_TAG
