name: Publish Helm Chart on Docker Success
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"] # Must match the 'name' inside build_docker_image_and_push.yml
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v4

      # We use the Run ID or SHA to ensure the Helm chart points to the exact image pushed
      - name: Package and Push Helm Chart
        run: |
          VERSION="0.1.${{ github.event.workflow_run.run_number }}"
          IMAGE_TAG="sha-${{ github.event.workflow_run.head_sha }}"
          
          helm package charts/booknow --version $VERSION --app-version $IMAGE_TAG
          helm push booknow-$VERSION.tgz oci://ghcr.io/${{ github.repository_owner }}/charts